name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  hygiene:
    name: RustFmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: fmt
      run: cargo fmt -- --check

  build:
    name: "Build, tests & clippy"
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y curl gcc libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build
    - name: Tests
      run: cargo test
    - name: All features
      run: cargo test --all-features
    - name: Clippy
      run: cargo clippy --tests --all-features -- --deny warnings
